Templates GET API & Basic QuantumLab Agent
Project-Quantum-Workspace/QuantumLab pull request #30
Opened 2023-08-28 10:42 UTC by QuanchiChen

1. Update the templates GET API endpoint to return all the authorised templates.
2. Develop QuantumLab Agent.
3. Develop the agent POST API endpoint.

2023-08-28 11:28 UTC, StevenDB995 approved these changes

2023-08-29 02:01 UTC, lois-ekd81194 approved these changes

2023-08-29 02:17 UTC, VortexMashiro requested changes
Please do some small changes refer to comments :)

2023-08-29 02:17 UTC, VortexMashiro commented on agent/config.yaml
> +metadata:
please add example config to readme, not in repository

2023-08-29 02:17 UTC, VortexMashiro commented on agent/go.mod
> +go 1.19
Use same version with Quantumlab main pls, which is 1.20

2023-08-29 02:17 UTC, VortexMashiro commented on agent/initialisation.sh
> +#!/bin/bash
same here, please add example files to readme

2023-08-31 07:37 UTC, VortexMashiro approved these changes

2023-08-31 07:51 UTC, merged