feat: User(Admin) information page and Admin Updating page
Project-Quantum-Workspace/QuantumLab pull request #31
Opened 2023-08-29 11:36 UTC by Davyyy

Connecting with Mock API, updating (put) passed network -200.

2023-08-29 11:43 UTC, StevenDB995 requested changes

2023-08-29 11:43 UTC, StevenDB995 commented on website/src/pages/AdminUpdate/admin.css
> +.avator{
typo: avatar

2023-08-29 11:43 UTC, StevenDB995 commented on website/src/pages/AdminUpdate/index.tsx
> +    console.log('click');
Please avoid using console.log. Delete them after testing

2023-08-29 11:43 UTC, StevenDB995 commented on website/src/pages/AdminUpdate/index.tsx
> +  //////////////////
Remove commented code segament. Keep your code clean

2023-08-29 11:43 UTC, StevenDB995 commented on website/src/pages/AdminView/adminView.css
> +.avator{
typo

2023-08-29 12:01 UTC, StevenDB995 approved these changes

2023-08-30 04:44 UTC, liuxt805 commented on website/src/pages/AdminView/index.tsx
> +  const url = 'https://my.api.mockaroo.com/data.json?key=e7cb8c20';
what is this url? shouldn't it be something like "/api/admin/users/:id"?

2023-08-30 04:44 UTC, liuxt805 commented on website/src/pages/AdminUpdate/index.tsx
> +  const posturl = 'https://my.api.mockaroo.com/data2.json?key=e7cb8c20&__method=PUT';
external api?

2023-08-30 04:44 UTC, liuxt805 commented on website/src/pages/AdminUpdate/index.tsx
> +  const posturl = 'https://my.api.mockaroo.com/data2.json?key=e7cb8c20&__method=PUT';
please implement mock api as well :))

2023-08-30 04:49 UTC, liuxt805 approved these changes

2023-08-30 04:50 UTC, merged