feat[template]: get preset icons
Project-Quantum-Workspace/QuantumLab pull request #38
Opened 2023-09-04 17:43 UTC by DNALOCK

2023-09-05 02:08 UTC, StevenDB995 requested changes
Some changes required and need to integrate with Quanchi's template functionalities before merging into main

2023-09-05 02:08 UTC, StevenDB995 commented on api/controller/template_controller.go
> +// @Router /templates/{id} [delete]
Wrong API doc. Shouldn't be a DELETE request

2023-09-05 02:08 UTC, StevenDB995 commented on api/controller/template_controller.go
> +		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to retrieve file list"})
Use model.ErrorResponse instead of gin.H

2023-09-05 05:27 UTC, StevenDB995 approved these changes

2023-09-06 03:24 UTC, edwardlin1695 approved these changes
Changes look good

2023-09-06 06:06 UTC, merged